apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
  nodeSelector:
    nodeType: privateNode

---
apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  selector:
    env: test
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
